name: gem_notes
description: Notas con AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_markdown: ^0.7.3+1
  hugeicons: ^0.0.7
  langchain: ^0.7.5
  langchain_community: ^0.3.1
  langchain_google: ^0.6.2
  meta: ^1.12.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  path_provider: ^2.1.4
  wolt_modal_sheet: ^0.9.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/

objectbox:
  output_dir: data/stores
